CREATE DATABASE OPCUS
GO

USE OPCUS
GO

CREATE TABLE USUARIO(
idUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeUsuario VARCHAR(15) NOT NULL,
Email VARCHAR(256) NOT NULL,
Cpf VARCHAR(10) NOT NULL,
Senha VARCHAR(10) NOT NULL,
TipoDePermissão VARCHAR(10) NOT NULL
);
GO

CREATE TABLE ARTISTAS(
idArtistas SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeArtistas VARCHAR(50) NOT NULL,
);
GO

CREATE TABLE ESTILOMUSICAL(
idEstMusical SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeEstMusical VARCHAR(20) NOT NULL
);
GO

CREATE TABLE EMPRESA(
idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
nomeEmpresa VARCHAR(50) NOT NULL
);
GO

CREATE TABLE CD(
idCD SMALLINT PRIMARY KEY IDENTITY(1,1),
idArtistas SMALLINT FOREIGN KEY REFERENCES ARTISTAS(idArtistas),
idEstMusical SMALLINT FOREIGN KEY REFERENCES ESTILOMUSICAL(idEstMusical),
nomeCD VARCHAR(50) NOT NULL
);
GO

CREATE TABLE ALBUM(
idALBUM SMALLINT PRIMARY KEY IDENTITY(1,1),
--idCD SMALLINT FOREIGN KEY REFERENCES CD(idCD),
idArtistas SMALLINT FOREIGN KEY REFERENCES ARTISTAS(idArtistas),
idEstMusical SMALLINT FOREIGN KEY REFERENCES ESTILOMUSICAL(idEstMusical),
nomeCD VARCHAR(50) NOT NULL
);
GO

ALTER TABLE ALBUM
DROP COLUMN nomeCD

ALTER TABLE ALBUM
ADD nomeAlbum VARCHAR(50) NOT NULL
