CREATE DATABASE PCLINICS_TARDE;
GO

USE PCLINICS_TARDE;
GO

CREATE TABLE VETERINARIO(
idVeterinario SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeVet VARCHAR(15) NOT NULL
);
GO

CREATE TABLE DONO(
idDono SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeDONO VARCHAR(15) NOT NULL
);
GO

CREATE TABLE TIPOPET(
idTipoPet SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeTPet VARCHAR(15) NOT NULL
);
GO

CREATE TABLE CLINICA(
idClinica SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeClinica VARCHAR(15) NOT NULL,
End_Clinica VARCHAR(100) NOT NULL
);
GO



CREATE TABLE RAÇA(
idRaça SMALLINT PRIMARY KEY IDENTITY(1,1),
idTipoPet SMALLINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
nomeRaça VARCHAR(15) NOT NULL
);
GO

CREATE TABLE PET(
idPet SMALLINT PRIMARY KEY IDENTITY(1,1),
idRaça SMALLINT FOREIGN KEY REFERENCES RAÇA(idRaça),
idDono SMALLINT FOREIGN KEY REFERENCES DONO(idDono),
nomeRaça VARCHAR(15) NOT NULL
);
GO

ALTER TABLE PET
DROP COLUMN nomeRaça

ALTER TABLE PET
ADD nomePet VARCHAR(20) NOT NULL



CREATE TABLE ATENDIMENTO(
idAtendimento SMALLINT PRIMARY KEY IDENTITY(1,1),
idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
);
GO

ALTER TABLE ATENDIMENTO
ADD Descricao VARCHAR(50) 

ALTER TABLE ATENDIMENTO
ADD DataAtend DATE

ALTER TABLE VETERINARIO
ADD idCLinica TINYINT

ALTER TABLE VETERINARIO
ADD CRMV SMALLINT
