CREATE DATABASE LOCADORA_TARDE;
GO

USE LOCADORA_TARDE;
GO


CREATE TABLE MARCA (
idMarca	SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeMarca VARCHAR(20) NOT NULL
);
GO

CREATE TABLE CLIENTE (
idCliente INT PRIMARY KEY IDENTITY(1,1),
nomeCliente VARCHAR(20) NOT NULL,
Cpf VARCHAR(20) NOT NULL
);
GO

CREATE TABLE MODELO (
idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
idMarca	SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
nomeModelo VARCHAR(15) NOT NULL
);
GO

CREATE TABLE VEICULOS(
idVeiculos INT PRIMARY KEY IDENTITY(1,1),
idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
Placa VARCHAR(10) NOT NULL
);
GO


CREATE TABLE ALUGUEL (
idAluguel INT PRIMARY KEY IDENTITY(1,1),
idCliente INT FOREIGN KEY REFERENCES CLIENTE(idCliente),
idVeiculos INT FOREIGN KEY REFERENCES VEICULOS(idVeiculos)
);
GO

CREATE TABLE EMPRESA(
idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
idVeiculos INT FOREIGN KEY REFERENCES VEICULOS(idVeiculos),
nomeEmpresa VARCHAR(15) NOT NULL 
);
GO

ALTER TABLE ALUGUEL
DROP Dataemissao DATE
GO

ALTER TABLE ALUGUEL
ADD DataDevolussao DATE 
